######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 6 19:53:43 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/m/d/mdinic/ec535/project/controller/. .

# Input
HEADERS += slidersgroup.h window.h
SOURCES += main.cpp slidersgroup.cpp window.cpp
